# netlify.toml
[build]
  command = "npm run build"
  publish = ".next"    # Netlify Next.js Runtime leest hieruit

[build.environment]
  NODE_VERSION = "18"

# (Optioneel) Netlify Functions instellingen
[functions]
  node_bundler = "esbuild"